#!/usr/bin/env php
<?php
//	License for all code of this FreePBX module can be found in the license file inside the module directory
//	Copyright 2013 Schmooze Com Inc.
//

// Bootstrap FreePBX but don't include any modules (so you won't get anything
// from the functions.inc.php files of all the modules.)
//
$restrict_mods = true;
include '/etc/freepbx.conf';
set_time_limit(0);
error_reporting(0);

// Connect to AGI:
//
require_once "phpagi.php";
$AGI = new AGI();
$AGI->answer();
$config = FreePBX::Alarmdialer()->getConfig();
usleep(500);
$cid = $AGI->parse_callerid();

//TODO: needs to use AMPUSER through macro-caller-id
alarmMenu($AGI, $cid['username']);

/**
 * The Alarm Administration Menu
 * @param  object $AGI    AGI Object
 * @param  string $number The "number" to work with
 */
function alarmMenu($AGI, $number) {
	sim_playback($AGI,"an-error-has-occurred");
	$AGI->hangup();
}


/**
 * Simulate playback functionality like the dialplan
 * @param  object $AGI  The AGI Object
 * @param  string $file Audio files combined by/with '&'
 */
function sim_playback($AGI, $file) {
	$files = explode('&',$file);
	foreach($files as $f) {
		$AGI->stream_file($f);
	}
}
